### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by flobb** [lechatquidanse/bicing-api#5]
Hello, interesting work !
In the readme, the link to http://jorgearco.com/ddd-with-symfony/ is broken as the article doesn't exists.

**Comment by lechatquidanse** [comment]
👍 I will fix it, thanks @florianbelhomme

**Comment by lechatquidanse** [comment]
The previous article doesnt exist anymore.
But the author has created a new SF4 boilerplate with CQRS, ES and DDD (https://github.com/jorge07/symfony-4-es-cqrs-boilerplate)
Fix in https://github.com/lechatquidanse/bicing-api/commit/82018ef1cd97bc9b6913d8130742492853152270
